CREATE TABLE IF NOT EXISTS messages (
  messageId INT PRIMARY KEY AUTO_INCREMENT,
  userId INT NOT NULL,
  messageText VARCHAR(500) NOT NULL,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (userId) REFERENCES usertable(userId),
  INDEX idx_createdAt (createdAt DESC)
);